---
name: loki
# replace with `bosh status --uuid`
director_uuid: c4f5c583-1bc3-427f-8ded-b3f5e107f970

# Graphite nozzle release is in our springernature organization. It is uploaded
# manually to Bosh from the repository (by pointing to the yml release file).
# You need to define the config/private.yml with the access keys to be able
# to read the bucket. The access key is in pe-pass
releases:
- name: loki
  version: latest

instance_groups:
- name: promtail
  instances: 1
  vm_type: small
  stemcell: trusty
  vm_extensions: []
  azs:
  - z1
  networks:
  - name: cf-dev-z1
  jobs:
  - name: promtail
    release: loki
  - name: loki
    release: loki
  properties:
    loki:
      credentials: |
        {
          "type": "service_account",
          "project_id": "sn-paas",
          "private_key_id": "55700b2e9d2408c092f528d4097e3a3100c35947",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCjrxsngJKpvhSE\nKAmazv1l4VpCHGXJ/r9D6HGgbjMvbKL9B1dpXFT2GKMz6I/pO5dafBXO9kuBS1xA\ncKhySvwsFVPEcHj7ce+UpPpfMBpuhlgzBGurkBJhS0ngJzroQ/lII/cEr2twPMci\nioV2eSPxtPbWZKyGxU9/gtWvsJd/Ii2llg82yehmDxM9EjBI2SvtHKxB7Bfs4phr\nB+b0e6cj4mbR8mRss2Eq/wh4PWV58lXAyKe1UTX/jnytk6znN9MfG9E1ikZEoZM5\nuXfFZAMnxIp9lNWmaraaDfVtR48Bh2HgkI5KKDpU4n8ujBNcl4F25YWmmTqtNSr4\nDJpXtedPAgMBAAECggEADUby6O1g+CvW9jFZNhl8LHtvGtW62/uyAAwmy2Ck/j/N\nqMCjsoQu0BeHhXpj0gNnb4uJKVSJI1+9h+ybfUnf0qOYO+LzrVG8oU4QkRAR1M1I\n8jp1kWEKXKICyA/mk1iQK+3e555jFKOZc4/Q658/7ydCrnlUFUqD/E/cjXfBkipO\nUJPG8IIO4Mabj6ox/7Kqtg/n7iJdxxEdcjzxyjTPswlkdFEMht9wizySPuE4J7Xg\nRjgbprngD1dBwyT6KMLWlcqpTEbla6+B++B+0LpK4l8r2zlOLXw0ZqT0wYhlYgFK\nRqfENlExx6IPzgqQfCQRXC+2oDTtNS8KGhD47MgIYQKBgQDXm01p8x9tqyj6CPuw\nSlGJAnHkFBZnbspvR4pToxu775o1o7MYsgpZxcBKWWS0eSwd4zCewUM8P8IYEcFn\nS7DNGexccwyWmLGy+h9U8vQPTUnXIwcidMucLI6bD3OxHpUAGG5LItHBob7H5IGu\n6W0OpsD3y/pNQLyILDOs/Tpb+wKBgQDCWYuCk/FlNkzxzF7Y5XTV7W4zkO0xrPSx\nWzyovYFYC5XYTDl59pGOfXZXF41rzjVdOv/FNILD8q9A23Lb9voNgJlAaqTmchrA\nTVoN9aJwc1NMLvbOaY+aMbfSQK+DPJTx3mFOOcMbnx0xmg8WHQkNSXIMByOUIuBN\nmjHGvmjNvQKBgHPddr2wNLyH1a6As1kqpyR81t2d2ehdxpYEmRaXOelGOtYGkdF8\npElYFx0daxv9XjL1i4RVEZ/IF7M9n3S2XV3rR3TrMuGfTyeCeOH66iNrAnqFzWi7\n4UudOkmkBSUy7RmvB16DaLupA1CCwRpRQRU1kc/YoztuxaJcNq0JLJqPAoGAQCfT\nF93CeAi+yasPPEYylVP1ZuxWgGl5tPpLQeCcy/W3F1nCN3KfhgwAfqt1sbq2fvo0\n6GJ3MDvyglRuzBHxZXeoH02U9cWA8y4VpjoJz1kijCmMq4LJNrtm1O8pgQcEm/su\n3+XNdFbIClGy3TfkfxBZp4LLyeDhbnySJetBKXkCgYEAquFV+9czseA/WMzk/egO\nKmNSDPtlGlXsIwb+7dBp+eEDQ5C9fJNob+qXfmIWtMd8pGr6oK9KdpZSCYdBtMGc\nqTJIQ/SSjbg6HCBRTbvhXcmOGCGIwKEekFkXim49I0cjzeH+KuxHe7e/I/AfSWy1\npI1S59PUReyD9leXFPvMXrg=\n-----END PRIVATE KEY-----\n",
          "client_email": "test-grafana-loki-941@sn-paas.iam.gserviceaccount.com",
          "client_id": "115244606617014747953",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/test-grafana-loki-941%40sn-paas.iam.gserviceaccount.com"
        }
      env:
        GOOGLE_APPLICATION_CREDENTIALS: '$CREDENTIALS'
      object_store: gcs
      object_store_params:
        bucket_name: test-loki-logging

stemcells:
- alias: trusty
  name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

